version: '3'
services:
  model-api:
    image: "deepset/covid-qa-haystack"
    ports:
      - "80:80"
    environment:
      - TEXT_FIELD_NAME=answer
      - SEARCH_FIELD_NAME=question
      - EXCLUDE_META_DATA_FIELDS=["question_emb"]
      # optional: use an embedding model instead of plain elasticsearch query
#      - EMBEDDING_FIELD_NAME=question_emb
#      - EMBEDDING_DIM=768
#      - EMBEDDING_MODEL_PATH=bert-base-uncased # MUST be the same as used for indexing the FAQs
      - USE_GPU=False
    command: /bin/sh -c "cd /home/user && sleep 20 && uvicorn covid-qa.api:app --host 0.0.0.0 --port 80 --limit-concurrency 10 --workers 1"
    network_mode: host
  elastic:
    image: "deepset/covid-qa-elastic"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node